from enum import Enum


class ClientActionType(Enum):
	RECEIVED_CARDS = 0
	RECEIVED_FLOWER_COUNT = 1
	DISCARD = 2
	RECEIVED_DISCARD_ACTION = 3
	RECEIVED_OTHER_PLAYER_GOT_CARD = 4
	PERFORM_CARD_ACTION = 5
	PERFORM_SELF_CARD_ACTION = 6
	RECEIVED_CONCEALED_KONG = 7
	RECEIVED_PLAYER_READY = 8
	WIN = 9