from enum import Enum


class ServerActionType(Enum):
	CHANGE_WIND = 0
	START_SEND_CARDS = 1
	START_FLOWER_REPLACEMENT = 2
	START_FLOWER_COUNT = 3
	SEND_CARD = 4
	FLOWER_REPLACEMENT = 5
	FLOWER_COUNT = 6
	WAIT_DISCARD = 7
	CLIENT_DISCARDED = 8