from enum import Enum


class ServerActionType(Enum):
	CHANGE_WIND = 0
	START_SEND_CARDS = 1
	START_FLOWER_REPLACEMENT = 2
	SEND_CARD = 3
	FLOWER_REPLACEMENT = 4
	WAIT_DISCARD = 5
	CLIENT_DISCARDED = 6
	OTHER_PLAYER_GOT_CARD = 7
	WAIT_CARD_ACTION  = 8
	CLIENT_PERFORMED_CARD_ACTION = 9